# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-07 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(choices=[('\uc7a1\ub2f4', '\uc7a1\ub2f4'), ('\ucef4\ud4e8\ud130', '\ucef4\ud4e8\ud130'), ('\uc601\ud654', '\uc601\ud654'), ('\uac8c\uc784', '\uac8c\uc784'), ('\ub4dc\ub77c\ub9c8', '\ub4dc\ub77c\ub9c8'), ('\ubb38\uc758', '\ubb38\uc758')], default='\uc7a1\ub2f4', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=main.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
