# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='classify',
            field=models.CharField(choices=[('Chat', '\uc7a1\ub2f4'), ('Computer', '\ucef4\ud4e8\ud130'), ('Movie', '\uc601\ud654'), ('Game', '\uac8c\uc784'), ('Drama', '\ub4dc\ub77c\ub9c8'), ('Suggest', '\ubb38\uc758')], default='\uc7a1\ub2f4', max_length=10),
        ),
    ]
